version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.node
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/src/app
